### PR TITLE
Use a GABBI_TEMPEST_PATH to locate gabbits

### PR DESCRIPTION
**Pull request by cdent**
In this way the plugin becomes generic: point it at some directories
that contain gabbi YAML files that use the provided environment
variables (see the README.rst), what them run.

One concern that will need to be address is dealing with parallelism:
tempest doesn't make it easy to manipulate the group_regex.

### CODE REVIEW

**Comment by cdent** [comment]
This is just a WIP for now, pushing it up so folk like @jd, @sileht and @markvoelker can have a looksee. The intent here is to make it super easy for tempest to run arbitrary gabbi yaml files, something discussed with @jd in the past.

**Review by jd — APPROVED** [review]
I like that. I don't know if it works but that's exactly what I had in mind since the beginning so it's cool to see it's possible!

**Comment by cdent** [comment]
> I don't know if it works

It works, at least for the file in the samples dir. The limiting factor at this point is other stuff that might be useful to pull from the tempest config and stick in `ENVIRON`, like the existing `FLAVOR_REF`. But a lot of that stuff can come from the environment set up by the user.

**Comment by markvoelker** [comment]
+1, I like the concept here. Very handy!  Agree with the concern around group_regex, but we'll just have to cross that bridge when we get to it.

**Comment by cdent** [comment]
Released a version of this to pypi: https://pypi.python.org/pypi/gabbi-tempest

So that there's something to experiment with.

**Pull request merged**
